services:
  scrumlr-backend:
    restart: always
    image: ghcr.io/inovex/scrumlr.io/scrumlr-server:5.0.0
    container_name: scrumlr-backend
    command:
      - "-disable-check-origin"
    environment:
      SCRUMLR_LOG_LEVEL: INFO
      SCRUMLR_SERVER_PORT: 8080
      SCRUMLR_INSECURE: "true"
      SCRUMLR_PRIVATE_KEY: "change_me"

      SCRUMLR_SERVER_DATABASE_URL: postgres://scrumlr:scrumlr123@postgres:5432/scrumlr?sslmode=disable
      SCRUMLR_SERVER_NATS_URL: nats://nats:4222

      SESSION_SECRET: "supersecret"

    depends_on:
      - postgres
      - nats

  scrumlr-frontend:
    restart: always
    image: ghcr.io/inovex/scrumlr.io/scrumlr-frontend:5.0.0
    container_name: scrumlr-frontend
    environment:
      SCRUMLR_LISTEN_PORT: 8080
      SCRUMLR_SERVER_URL: http://localhost:8081
      SCRUMLR_WEBSOCKET_URL: ws://localhost:8081
    depends_on:
      - scrumlr-backend
    ports:
      - "8081:8080"   # 👈 IMPORTANT (not 80)

  postgres:
    restart: always
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: scrumlr
      POSTGRES_USER: scrumlr
      POSTGRES_PASSWORD: scrumlr123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    restart: always
    image: nats:2.10
    container_name: nats

volumes:
  postgres_data:
